[package]
name = "org-pulse"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = { version = "0.4.41", features = ["serde"] }
confy = "1.0.0"
octocrab = "0.44.1"
regex = "1.11.1"
serde = "1.0.219"
tokio = { version = "1.47.0", features = ["full"] }
