PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS orgs (
  id INTEGER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS contributors (
  id INTEGER PRIMARY KEY NOT NULL,
  username TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS repos (
  id INTEGER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  org_id INTEGER NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  UNIQUE(name, org_id)
);

CREATE TABLE IF NOT EXISTS scrapes (
  id INTEGER PRIMARY KEY NOT NULL,
  start_dt DATETIME NOT NULL,
  end_dt DATETIME NOT NULL,
);

CREATE TABLE IF NOT EXISTS repo_scrapes (
  id INTEGER PRIMARY KEY NOT NULL,
  scrape_id INTEGER NOT NULL REFERENCES scrapes(id) ON DELETE CASCADE,
  org_id INTEGER NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  repo_id INTEGER NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
  commits INTEGER NOT NULL DEFAULT 0,
  prs INTEGER NOT NULL DEFAULT 0,
  lines INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS contributor_scrapes (
  id INTEGER PRIMARY KEY NOT NULL,
  repo_scrape_id INTEGER NOT NULL REFERENCES repo_scrapes(id) ON DELETE CASCADE,
  contributor_id INTEGER NOT NULL REFERENCES contributors(id) ON DELETE CASCADE,
  commits INTEGER NOT NULL DEFAULT 0,
  lines INTEGER NOT NULL DEFAULT 0
);
